services:
  - type: web
    name: union
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - ./
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: union-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: union-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: union-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: union-db
          property: password
    postDeploy: |
      php artisan migrate --force
      php artisan storage:link
      php artisan queue:restart
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan optimize
